on:
  issues:
    types: [labeled]

jobs:
  automate_invite:
    runs-on: ubuntu-latest
    steps:
      - name: Invite on label
        uses: vj-abigo/invite-on-label@v1.4
        with:
          organization: kappital
          label: membership-approved
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          comment: 'Welcome onboard'
        env:
          INVITE_TOKEN: ${{ secrets.INVITE_TOKEN }}
